version: "3.8"

services:

  database:
    image: postgres:15
    container_name: financial-system_database
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      .env
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - app_network


networks:
  app_network:
    driver: bridge
