spring:
  application:
    name: financial-system
  datasource:
    url: jdbc:postgresql://localhost:5432/financial-system
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      platform: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true


server:
  error:
    include-stacktrace: always
  port: 8080
  ssl:
    enabled: false

jwt:
  secret: minhaChaveSuperSecretaDeNoMinimo32Caracteres
  expiration-time: 36000000